import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {realEstateRetrieval} from '../lib/claus-ai/real-estate-retrieval.ts';
import {realEstateProposals} from '../lib/real-estate-extraction.ts';
function fixture(){const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8').replaceAll('--> statement-breakpoint',''));
 sqlite.prepare("INSERT INTO contacts(id,first_name,last_name,intent) VALUES(1,'Buyer','One','Buyer'),(2,'Seller','Two','Seller')").run();sqlite.prepare("INSERT INTO properties(id,contact_id,address,bedrooms,bathrooms,square_footage,year_built,key_features) VALUES(1,2,'123 Example Lane',4,3,2800,2004,'Large lot')").run();
 sqlite.prepare("INSERT INTO transactions(id,contact_id,property_id,side,status,property_address,current_price,original_list_price,number_of_showings,number_of_offers,listing_activity_notes,showing_feedback) VALUES(1,2,1,'SELLER','Active','123 Example Lane',599900,599900,14,0,'Repairs complete','Buyers liked the lot but wanted a lower price')").run();
 const db={prepare(sql){let args=[];const stmt=sqlite.prepare(sql);return {bind(...a){args=a;return this;},async all(){return {results:stmt.all(...args)}},async first(){return stmt.get(...args)||null},async run(){const r=stmt.run(...args);return {meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}}},sqlite};return db;}
test('all migrations apply with foreign keys and complete seller property saves',()=>{const {sqlite}=fixture();const p=sqlite.prepare('SELECT * FROM properties WHERE id=1').get();assert.equal(p.bedrooms,4);assert.equal(p.square_footage,2800);assert.equal(p.year_built,2004);assert.deepEqual(sqlite.prepare('PRAGMA foreign_key_check').all(),[]);sqlite.close();});
test('price history and two transactions retain separate lifecycles',()=>{const {sqlite}=fixture();sqlite.prepare("INSERT INTO real_estate_history(entity_type,entity_id,contact_id,transaction_id,field_name,old_value,new_value,changed_by,source) VALUES('transaction',1,2,1,'current_price','599900','589900','Brad Claus','manual')").run();sqlite.prepare('UPDATE transactions SET current_price=589900,revision=revision+1 WHERE id=1 AND revision=0').run();sqlite.prepare("INSERT INTO transactions(contact_id,side,status,property_address,close_date) VALUES(2,'BUYER','Closed','2019 purchase','2019-09-01')").run();assert.equal(sqlite.prepare('SELECT count(*) n FROM transactions WHERE contact_id=2').get().n,2);assert.equal(sqlite.prepare('SELECT current_price FROM transactions WHERE id=1').get().current_price,589900);assert.equal(sqlite.prepare('SELECT old_value FROM real_estate_history').get().old_value,'599900');assert.equal(sqlite.prepare('SELECT revision FROM transactions WHERE id=1').get().revision,1);sqlite.close();});
test('structured buyer max and one-story criteria use authoritative numeric fields',async()=>{const db=fixture();db.sqlite.prepare("INSERT INTO buyer_profiles(contact_id,price_max,bedrooms_needed,target_areas_zip_codes,must_haves,one_story_preference) VALUES(1,450000,4,'Schertz/Cibolo','One story',1)").run();let r=await realEstateRetrieval(db,'Which buyers have a max price under $500,000?',[]);assert.equal(r.records.length,1);assert.equal(r.records[0].price_max,450000);assert.equal(r.records[0].kind,'buyer_profile');r=await realEstateRetrieval(db,'Who wants a one-story home?',[]);assert.equal(r.records[0].one_story_preference,1);db.sqlite.close();});
test('hybrid listing feedback scopes narrative search to exact matching transactions',async()=>{const db=fixture();const r=await realEstateRetrieval(db,'Which listings had lots of showings but no offers, and what feedback did buyers give?',[]);assert.deepEqual(r.transactionIds,[1]);assert.equal(r.records[0].number_of_showings,14);assert.match(r.records[0].body,/lower price/);assert.ok(r.tools.includes('real_estate_narrative_search'));assert.match(r.thresholdNote,/more than 10/);db.sqlite.close();});
test('edited notes invalidate affected chunks, preserve unrelated chunks and remove deleted vectors',()=>{const db=fixture();db.sqlite.prepare("INSERT INTO claus_ai_embeddings(source_kind,source_id,contact_id,content_hash,provider,model,vector_json,content) VALUES('transaction',1,2,'a','openai','test','[]','Old'),('property',1,2,'b','openai','test','[]','Keep')").run();db.sqlite.prepare("UPDATE transactions SET listing_activity_notes='Fresh notes' WHERE id=1").run();assert.equal(db.sqlite.prepare("SELECT count(*) n FROM claus_ai_embeddings WHERE source_kind='transaction'").get().n,0);assert.equal(db.sqlite.prepare("SELECT count(*) n FROM claus_ai_embeddings WHERE source_kind='property'").get().n,1);assert.equal(db.sqlite.prepare("SELECT status FROM claus_ai_index_queue WHERE source_key='transaction:1'").get().status,'pending');db.sqlite.prepare('DELETE FROM transactions WHERE id=1').run();assert.equal(db.sqlite.prepare("SELECT count(*) n FROM claus_ai_index_queue WHERE source_key='transaction:1'").get().n,0);db.sqlite.close();});
test('explicit price and bedroom statements are proposals only',()=>{assert.equal(realEstateProposals("We're dropping the price to $575,000.")[0].fieldName,'current_price');assert.equal(realEstateProposals('We really need four bedrooms now.')[0].fieldValue,'4');});
