import { authorizeCrmOwner } from '@/lib/crm-auth';
import { db, migrateExisting, saveEntity, transactionDetail, transactionList, validated } from '@/lib/real-estate';
import { transactionGroups,propertyGroups,transactionStatuses } from '@/lib/real-estate-fields';
export async function GET(request:Request){const auth=await authorizeCrmOwner();if(auth.denied)return auth.denied;try{await migrateExisting();const p=new URL(request.url).searchParams;const id=Number(p.get('id'));return Response.json(id?await transactionDetail(id):{transactions:await transactionList(Number(p.get('contactId'))||undefined)},{headers:{'cache-control':'no-store'}});}catch{return Response.json({error:'Transactions could not be loaded.'},{status:503});}}
export async function POST(request:Request){const auth=await authorizeCrmOwner();if(auth.denied)return auth.denied;try{const b=await request.json() as Record<string,any>;
 if(b.action==='create'){const contactId=Number(b.contactId);if(!Number.isSafeInteger(contactId)||!await db().prepare('SELECT id FROM contacts WHERE id=?').bind(contactId).first())throw Error('Choose a client');if(!['SELLER','BUYER'].includes(b.side)||!String(b.address||'').trim())throw Error('Choose a side and property address');
 const result=await db().prepare("INSERT INTO transactions(contact_id,side,status,property_address,lead_source,agent,source_system) SELECT ?,?,'Active',?,lead_source,'Brad Claus','manual' FROM contacts WHERE id=?").bind(contactId,b.side,String(b.address).trim(),contactId).run();const id=Number(result.meta.last_row_id);
 const existing=await db().prepare('SELECT id FROM properties WHERE lower(trim(address))=lower(trim(?)) LIMIT 1').bind(String(b.address).trim()).first<{id:number}>();const propertyId=existing?.id||Number((await db().prepare("INSERT INTO properties(contact_id,address,relationship,source_system) VALUES(?,?,?,'manual')").bind(contactId,String(b.address).trim(),b.side).run()).meta.last_row_id);
 await db().prepare('UPDATE transactions SET property_id=? WHERE id=?').bind(propertyId,id).run();return Response.json({id});
 }
 if(b.action==='attach_property'){const tx=await db().prepare('SELECT * FROM transactions WHERE id=?').bind(Number(b.id)).first<Record<string,any>>();if(!tx)throw Error('Transaction missing');if(tx.property_id)throw Error('Property already linked; reload');const address=String(b.values?.address||tx.property_address||'').trim();if(!address)throw Error('Enter the property address');const v=validated(b.values||{},propertyGroups);const keys=Object.keys(v);const result=await db().prepare(`INSERT INTO properties(contact_id,address,source_system${keys.length?','+keys.join(','):''}) VALUES(?,?,'manual'${keys.map(()=>',?').join('')})`).bind(tx.contact_id,address,...Object.values(v)).run();await db().prepare('UPDATE transactions SET property_id=?,property_address=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND property_id IS NULL').bind(result.meta.last_row_id,address,tx.id).run();return Response.json({ok:true});}
 if(b.action==='save'){await saveEntity(b.kind,Number(b.id),b.values||{},Number(b.revision));return Response.json({ok:true});}
 if(b.action==='link'||b.action==='unlink'){const id=Number(b.id),recordId=Number(b.recordId);if(!await transactionDetail(id))throw Error('Transaction missing');if(!['task','communication','contact'].includes(b.kind)||!Number.isSafeInteger(recordId))throw Error('Choose a record');const table=b.kind==='task'?'tasks':b.kind==='contact'?'contacts':'communications';if(!await db().prepare(`SELECT id FROM ${table} WHERE id=?`).bind(recordId).first())throw Error('Record missing');
 if(b.kind==='contact'){await db().prepare(b.action==='link'?'INSERT INTO transaction_contacts(transaction_id,contact_id) VALUES(?,?) ON CONFLICT DO NOTHING':'DELETE FROM transaction_contacts WHERE transaction_id=? AND contact_id=?').bind(id,recordId).run();}else await db().prepare(b.action==='link'?'INSERT INTO transaction_links(transaction_id,kind,record_id) VALUES(?,?,?) ON CONFLICT DO NOTHING':'DELETE FROM transaction_links WHERE transaction_id=? AND kind=? AND record_id=?').bind(id,b.kind,recordId).run();return Response.json({ok:true});}
 throw Error('Unknown action');
 }catch(e){return Response.json({error:e instanceof Error?e.message:'Could not save transaction'},{status:400});}}
