import {
  index,
  uniqueIndex,
  integer,
  real,
  sqliteTable,
  text,
} from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
export const contacts = sqliteTable("contacts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  phone: text("phone"),
  email: text("email"),
  displayName: text("display_name"),
  additionalPhones: text("additional_phones"),
  phoneType: text("phone_type"),
  additionalEmails: text("additional_emails"),
  emailType: text("email_type"),
  spouseName: text("spouse_name"),
  updatedBy: text("updated_by"),
  updateSource: text("update_source"),
  address: text("address"),
  preferredContact: text("preferred_contact"),
  relationship: text("relationship").notNull().default("Lead"),
  leadSource: text("lead_source"),
  leadSourceDetail: text("lead_source_detail"),
  campaign: text("campaign"),
  smsConsent: integer("sms_consent").notNull().default(0),
  smsOptOut: integer("sms_opt_out").notNull().default(0),
  emailConsent: integer("email_consent").notNull().default(0),
  emailUnsubscribed: integer("email_unsubscribed").notNull().default(0),
  adLandingPage: text("ad_landing_page"),
  intent: text("intent").notNull().default("Unknown"),
  targetLocations: text("target_locations"),
  priceRange: text("price_range"),
  financingType: text("financing_type"),
  preApproved: integer("pre_approved", { mode: "boolean" }),
  desiredProperty: text("desired_property"),
  desiredMoveDate: text("desired_move_date"),
  propertyAddress: text("property_address"),
  sellingTimeline: text("selling_timeline"),
  sellingReason: text("selling_reason"),
  propertyStatus: text("property_status"),
  relationshipSummary: text("relationship_summary"),
  motivation: text("motivation"),
  concerns: text("concerns"),
  objections: text("objections"),
  contextualNotes: text("contextual_notes"),
  estimatedTimeline: text("estimated_timeline"),
  temperature: text("temperature").notNull().default("Warm"),
  lastMeaningfulContact: text("last_meaningful_contact"),
  nextFollowUp: text("next_follow_up"),
  recommendedNextAction: text("recommended_next_action"),
  lastAiSummaryAt: text("last_ai_summary_at"),
  tags: text("tags"),
  externalFubId: text("external_fub_id"),
  sourceSystem: text("source_system"),
  importJobId: integer("import_job_id"),
  birthday: text("birthday"),
  dateAdded: text("date_added"),
  stage: text("stage"),
  timeframe: text("timeframe"),
  isSample: integer("is_sample", { mode: "boolean" }).notNull().default(false),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
  updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP"),
});

export const importJobs = sqliteTable(
  "import_jobs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    fileName: text("file_name").notNull(),
    sourceSystem: text("source_system").notNull(),
    totalRows: integer("total_rows").notNull().default(0),
    importedRecords: integer("imported_records").notNull().default(0),
    updatedRecords: integer("updated_records").notNull().default(0),
    skippedRecords: integer("skipped_records").notNull().default(0),
    duplicateRecords: integer("duplicate_records").notNull().default(0),
    errorCount: integer("error_count").notNull().default(0),
    warningCount: integer("warning_count").notNull().default(0),
    status: text("status").notNull().default("Processing"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
    completedAt: text("completed_at"),
    rolledBackAt: text("rolled_back_at"),
  },
  (t) => [index("idx_import_jobs_created_at").on(t.createdAt)],
);

export const importRows = sqliteTable(
  "import_rows",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    importJobId: integer("import_job_id").notNull().references(() => importJobs.id),
    rowNumber: integer("row_number").notNull(),
    externalFubId: text("external_fub_id"),
    contactId: integer("contact_id").references(() => contacts.id),
    status: text("status").notNull(),
    matchType: text("match_type"),
    warning: text("warning"),
    error: text("error"),
    rawJson: text("raw_json").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => [
    index("idx_import_rows_job").on(t.importJobId),
    index("idx_import_rows_external_fub").on(t.externalFubId),
  ],
);

export const contactMethods = sqliteTable(
  "contact_methods",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contactId: integer("contact_id").notNull().references(() => contacts.id),
    importJobId: integer("import_job_id").references(() => importJobs.id),
    kind: text("kind").notNull(),
    value: text("value").notNull(),
    normalizedValue: text("normalized_value"),
    label: text("label"),
    sourceSystem: text("source_system"),
    isPrimary: integer("is_primary", { mode: "boolean" }).notNull().default(false),
  },
  (t) => [index("idx_contact_methods_contact").on(t.contactId)],
);

export const contactRelationships = sqliteTable(
  "contact_relationships",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contactId: integer("contact_id").notNull().references(() => contacts.id),
    relatedContactId: integer("related_contact_id").references(() => contacts.id),
    importJobId: integer("import_job_id").references(() => importJobs.id),
    relationshipType: text("relationship_type").notNull(),
    relatedFirstName: text("related_first_name"),
    relatedLastName: text("related_last_name"),
    sourceSystem: text("source_system"),
    sourceField: text("source_field"),
    sourceDate: text("source_date"),
  },
  (t) => [index("idx_contact_relationships_contact").on(t.contactId)],
);

export const contactIntelligence = sqliteTable(
  "contact_intelligence",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contactId: integer("contact_id").notNull().references(() => contacts.id),
    importJobId: integer("import_job_id").references(() => importJobs.id),
    category: text("category").notNull(),
    fieldName: text("field_name").notNull(),
    value: text("value").notNull(),
    status: text("status").notNull().default("Current"),
    sourceSystem: text("source_system").notNull(),
    sourceRecordId: text("source_record_id"),
    sourceField: text("source_field"),
    sourceDate: text("source_date"),
    confidence: real("confidence").notNull().default(1),
    supersededAt: text("superseded_at"),
  },
  (t) => [index("idx_contact_intelligence_contact").on(t.contactId)],
);

export const relationshipMoments = sqliteTable(
  "relationship_moments",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contactId: integer("contact_id").notNull().references(() => contacts.id),
    importJobId: integer("import_job_id").references(() => importJobs.id),
    type: text("type").notNull(),
    dateValue: text("date_value").notNull(),
    label: text("label").notNull(),
    sourceSystem: text("source_system").notNull(),
    sourceRecordId: text("source_record_id"),
  },
  (t) => [index("idx_relationship_moments_contact").on(t.contactId)],
);
export const opportunities = sqliteTable(
  "opportunities",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contactId: integer("contact_id")
      .notNull()
      .references(() => contacts.id),
    type: text("type").notNull(),
    stage: text("stage").notNull(),
    estimatedPrice: real("estimated_price"),
    estimatedCommission: real("estimated_commission"),
    probability: integer("probability"),
    expectedTimeframe: text("expected_timeframe"),
    propertyAddress: text("property_address"),
    notes: text("notes"),
    details: text("details"),
    updatedBy: text("updated_by"),
    updateSource: text("update_source"),
    importJobId: integer("import_job_id").references(() => importJobs.id),
    sourceSystem: text("source_system"),
    sourceRecordId: text("source_record_id"),
    isSample: integer("is_sample", { mode: "boolean" })
      .notNull()
      .default(false),
    createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
    updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP"),
  },
  (t) => [
    index("idx_opportunities_contact_id").on(t.contactId),
    index("idx_opportunities_stage").on(t.stage),
  ],
);
export const tasks = sqliteTable(
  "tasks",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contactId: integer("contact_id").references(() => contacts.id),
    opportunityId: integer("opportunity_id").references(() => opportunities.id),
    title: text("title").notNull(),
    type: text("type").notNull().default("Task"),
    dueDate: text("due_date"),
    dueTime: text("due_time"),
    priority: text("priority").notNull().default("Normal"),
    status: text("status").notNull().default("Open"),
    notes: text("notes"),
    details: text("details"),
    updatedAt: text("updated_at"),
    updatedBy: text("updated_by"),
    updateSource: text("update_source"),
    sourceSystem: text("source_system"),
    sourceRecordId: text("source_record_id"),
    aiExtracted: integer("ai_extracted", { mode: "boolean" }).notNull().default(false),
    isSample: integer("is_sample", { mode: "boolean" })
      .notNull()
      .default(false),
    createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
    completedAt: text("completed_at"),
    microsoftEventId: text("microsoft_event_id"),
    microsoftCalendarId: text("microsoft_calendar_id"),
    calendarSyncStatus: text("calendar_sync_status"),
    calendarSyncError: text("calendar_sync_error"),
    lastCalendarSyncAt: text("last_calendar_sync_at"),
    calendarTransactionId: text("calendar_transaction_id"),
    calendarChangeKey: text("calendar_change_key"),
  },
  (t) => [
    index("idx_tasks_status_due_date").on(t.status, t.dueDate),
    index("idx_tasks_contact_id").on(t.contactId),
  ],
);
export const notes = sqliteTable(
  "notes",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contactId: integer("contact_id")
      .notNull()
      .references(() => contacts.id),
    body: text("body").notNull(),
    importJobId: integer("import_job_id").references(() => importJobs.id),
    sourceSystem: text("source_system"),
    sourceRecordId: text("source_record_id"),
    isSample: integer("is_sample", { mode: "boolean" })
      .notNull()
      .default(false),
    createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
  },
  (t) => [index("idx_notes_contact_created").on(t.contactId, t.createdAt)],
);
export const communications = sqliteTable(
  "communications",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contactId: integer("contact_id").references(() => contacts.id),
    type: text("type").notNull(),
    direction: text("direction").notNull(),
    occurredAt: text("occurred_at").notNull(),
    subject: text("subject"),
    messageTranscript: text("message_transcript"),
    durationSeconds: integer("duration_seconds"),
    recordingUrl: text("recording_url"),
    recordingId: text("recording_id"),
    aiSummary: text("ai_summary"),
    callOutcome: text("call_outcome"),
    followUpSuggestion: text("follow_up_suggestion"),
    externalProviderId: text("external_provider_id").unique(),
    fromNumber: text("from_number"),
    toNumber: text("to_number"),
    callerNumber: text("caller_number"),
    destinationNumber: text("destination_number"),
    bradCellNumber: text("brad_cell_number"),
    businessNumber: text("business_number"),
    callControlId: text("call_control_id"),
    callLegId: text("call_leg_id"),
    relatedCallLegIds: text("related_call_leg_ids"),
    startedAt: text("started_at"),
    answeredAt: text("answered_at"),
    bridgedAt: text("bridged_at"),
    endedAt: text("ended_at"),
    status: text("status"),
    importJobId: integer("import_job_id").references(() => importJobs.id),
    sourceSystem: text("source_system"),
    sourceRecordId: text("source_record_id"),
    participants: text("participants"),
    imported: integer("imported", { mode: "boolean" }).notNull().default(false),
    originalImportedText: text("original_imported_text"),
    audioObjectKey: text("audio_object_key"),
    audioContentType: text("audio_content_type"),
    interactionType: text("interaction_type"),
    authorName: text("author_name"),
    transcriptionStatus: text("transcription_status"),
    transcriptTimestamps: text("transcript_timestamps"),
    analysisStatus: text("analysis_status"),
    isSample: integer("is_sample", { mode: "boolean" })
      .notNull()
      .default(false),
  },
  (t) => [
    index("idx_communications_contact_id").on(t.contactId),
    index("idx_communications_call_control_id").on(t.callControlId),
  ],
);
export const communicationSuggestions = sqliteTable(
  "communication_suggestions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    communicationId: integer("communication_id")
      .notNull()
      .references(() => communications.id),
    category: text("category").notNull(),
    title: text("title").notNull(),
    detail: text("detail"),
    dueDate: text("due_date"),
    dueTime: text("due_time"),
    daypart: text("daypart"),
    schedulingPrecision: text("scheduling_precision"),
    fieldName: text("field_name"),
    fieldValue: text("field_value"),
    status: text("status").notNull().default("Suggested"),
    commitment: integer("commitment", { mode: "boolean" }).notNull().default(false),
    sourceExcerpt: text("source_excerpt"),
    needsReview: integer("needs_review", { mode: "boolean" }).notNull().default(false),
    aiExtracted: integer("ai_extracted", { mode: "boolean" }).notNull().default(true),
    acceptedBy: text("accepted_by"),
    acceptedAt: text("accepted_at"),
    originalValue: text("original_value"),
    editedBy: text("edited_by"),
    editedAt: text("edited_at"),
    dismissalReason: text("dismissal_reason"),
    createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
  },
  (t) => [index("idx_suggestions_communication").on(t.communicationId)],
);
export const properties = sqliteTable("properties", {
  street: text("street"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  mls_number: text("mls_number"),
  property_type: text("property_type"),
  subdivision: text("subdivision"),
  bedrooms: real("bedrooms"),
  bathrooms: real("bathrooms"),
  square_footage: real("square_footage"),
  lot_size: text("lot_size"),
  year_built: real("year_built"),
  builder_name: text("builder_name"),
  garage_size: real("garage_size"),
  hoa_name: text("hoa_name"),
  hoa_amount: real("hoa_amount"),
  occupancy_status: text("occupancy_status"),
  warranty_provider: text("warranty_provider"),
  key_features: text("key_features"),
  description: text("description"),
  updatedAt: text("updated_at"),
  revision: integer("revision").notNull().default(0),
  id: integer("id").primaryKey({ autoIncrement: true }),
  contactId: integer("contact_id")
    .notNull()
    .references(() => contacts.id),
  address: text("address").notNull(),
  relationship: text("relationship"),
  status: text("status"),
  notes: text("notes"),
  importJobId: integer("import_job_id").references(() => importJobs.id),
  sourceSystem: text("source_system"),
  externalRecordId: text("external_record_id"),
  isSample: integer("is_sample", { mode: "boolean" }).notNull().default(false),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
});
export const activities = sqliteTable(
  "activities",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    contactId: integer("contact_id")
      .notNull()
      .references(() => contacts.id),
    type: text("type").notNull(),
    title: text("title").notNull(),
    detail: text("detail"),
    occurredAt: text("occurred_at").notNull().default("CURRENT_TIMESTAMP"),
    sourceId: integer("source_id"),
    isSample: integer("is_sample", { mode: "boolean" })
      .notNull()
      .default(false),
  },
  (t) => [
    index("idx_activities_contact_occurred").on(t.contactId, t.occurredAt),
  ],
);

export const clausAiTurns = sqliteTable("claus_ai_turns", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: text("user_id"),
  conversationId: text("conversation_id").notNull(),
  question: text("question").notNull(),
  answer: text("answer"),
  tools: text("tools"),
  evidence: text("evidence"),
  provider: text("provider"),
  model: text("model"),
  usage: text("usage"),
  elapsedMs: integer("elapsed_ms"),
  error: text("error"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => [index("idx_ai_turns_conversation").on(t.conversationId, t.id)]);

export const clausAiDrafts = sqliteTable("claus_ai_drafts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  turnId: integer("turn_id").references(() => clausAiTurns.id),
  contactId: integer("contact_id").notNull().references(() => contacts.id),
  communicationId: integer("communication_id").notNull().references(() => communications.id),
  medium: text("medium").notNull(),
  generatedDraft: text("generated_draft").notNull(),
  factsUsed: text("facts_used"),
  openQuestions: text("open_questions"),
  riskFlags: text("risk_flags"),
  status: text("status").notNull().default("Suggested"),
  finalVersion: text("final_version"),
  reviewedAt: text("reviewed_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => [index("idx_ai_drafts_communication").on(t.communicationId)]);

export const clausAiEmbeddings = sqliteTable("claus_ai_embeddings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  sourceKind: text("source_kind").notNull(),
  sourceId: integer("source_id").notNull(),
  contactId: integer("contact_id"),
  occurredAt: text("occurred_at"),
  contentHash: text("content_hash").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  vectorJson: text("vector_json").notNull(),
  chunkIndex: integer("chunk_index").notNull().default(0),
  content: text("content"),
  sourceType: text("source_type"),
  sender: text("sender"),
  recipient: text("recipient"),
  threadId: text("thread_id"),
  metadataJson: text("metadata_json"),
  indexedAt: text("indexed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => [uniqueIndex("idx_ai_embedding_source_chunk_model").on(t.sourceKind, t.sourceId, t.chunkIndex, t.provider, t.model)]);

export const clausAiIndexQueue = sqliteTable("claus_ai_index_queue", {
  sourceKind: text("source_kind").notNull(),
  sourceId: integer("source_id").notNull(),
  status: text("status").notNull().default("pending"),
  error: text("error"),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  primaryKey: text("source_key").primaryKey(),
});
export const telnyxEvents = sqliteTable(
  "telnyx_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    eventId: text("event_id").notNull().unique(),
    eventType: text("event_type").notNull(),
    callControlId: text("call_control_id"),
    callLegId: text("call_leg_id"),
    callSessionId: text("call_session_id"),
    fromNumber: text("from_number"),
    toNumber: text("to_number"),
    direction: text("direction"),
    payload: text("payload").notNull(),
    receivedAt: text("received_at")
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => [
    index("idx_telnyx_events_received_at").on(t.receivedAt),
    index("idx_telnyx_events_type_received").on(t.eventType, t.receivedAt),
  ],
);
export const webrtcPresence = sqliteTable("webrtc_presence", {
  id: text("id").primaryKey(),
  lastSeen: text("last_seen")
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  connected: integer("connected", { mode: "boolean" }).notNull().default(false),
});
export const telnyxWebrtcCredentials = sqliteTable(
  "telnyx_webrtc_credentials",
  {
    identity: text("identity").primaryKey(),
    credentialId: text("credential_id").notNull().unique(),
    sipUsername: text("sip_username").notNull(),
    expiresAt: text("expires_at"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
  },
);
export const telnyxCallFlows = sqliteTable(
  "telnyx_call_flows",
  {
    id: text("id").primaryKey(),
    communicationId: integer("communication_id")
      .notNull()
      .references(() => communications.id),
    direction: text("direction").notNull(),
    contactId: integer("contact_id").references(() => contacts.id),
    contactNumber: text("contact_number"),
    callSessionId: text("call_session_id").unique(),
    primaryCallControlId: text("primary_call_control_id"),
    bradCallControlId: text("brad_call_control_id"),
    contactCallControlId: text("contact_call_control_id"),
    connectionId: text("connection_id").notNull(),
    status: text("status").notNull(),
    createdAt: text("created_at")
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
  },
  (t) => [
    index("idx_telnyx_call_flows_communication").on(t.communicationId),
    index("idx_telnyx_call_flows_session").on(t.callSessionId),
  ],
);

export const microsoftMailConnections = sqliteTable("microsoft_mail_connections", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ownerUserId: text("owner_user_id").notNull(),
  mailbox: text("mailbox").notNull(),
  graphUserId: text("graph_user_id").notNull(),
  encryptedRefreshToken: text("encrypted_refresh_token").notNull(),
  sendEnabled: integer("send_enabled").notNull().default(0),
  calendarEnabled: integer("calendar_enabled").notNull().default(0),
  subscriptionId: text("subscription_id"),
  clientState: text("client_state"),
  subscriptionExpiresAt: text("subscription_expires_at"),
  lastSyncedAt: text("last_synced_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, t => [uniqueIndex("idx_microsoft_mail_connections_mailbox").on(t.mailbox)]);

export const microsoftOauthStates = sqliteTable("microsoft_oauth_states", {
  state: text("state").primaryKey(),
  ownerUserId: text("owner_user_id").notNull(),
  verifier: text("verifier").notNull(),
  expiresAt: text("expires_at").notNull(),
});

export const aiUsage = sqliteTable("ai_usage", {
  id: text("id").primaryKey(),
  createdAt: text("created_at").notNull(),
  billingDay: text("billing_day").notNull(),
  billingMonth: text("billing_month").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  tier: text("tier").notNull(),
  taskType: text("task_type").notNull(),
  contactId: integer("contact_id"),
  sourceId: text("source_id"),
  inputTokens: integer("input_tokens").notNull().default(0),
  outputTokens: integer("output_tokens").notNull().default(0),
  cachedTokens: integer("cached_tokens").notNull().default(0),
  reservedUsd: real("reserved_usd").notNull(),
  estimatedUsd: real("estimated_usd").notNull(),
  actualUsd: real("actual_usd"),
  status: text("status").notNull(),
  errorCode: text("error_code"),
}, t => [index("idx_ai_usage_day").on(t.billingDay), index("idx_ai_usage_month").on(t.billingMonth), index("idx_ai_usage_task").on(t.taskType)]);

export const aiSettings = sqliteTable("ai_settings", {
  id: integer("id").primaryKey(),
  monthlyTargetUsd: real("monthly_target_usd"),
  monthlyWarningUsd: real("monthly_warning_usd"),
  monthlyHardLimitUsd: real("monthly_hard_limit_usd"),
  dailyHardLimitUsd: real("daily_hard_limit_usd"),
  maxRequestCostUsd: real("max_request_cost_usd"),
  autoGenerateMessageDrafts: integer("auto_generate_message_drafts", { mode: "boolean" }).notNull().default(false),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const pushSubscriptions = sqliteTable("push_subscriptions", {
  endpoint: text("endpoint").primaryKey(),
  ownerUserId: text("owner_user_id").notNull(),
  p256dh: text("p256dh").notNull(),
  auth: text("auth").notNull(),
  deviceName: text("device_name"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const pushSettings = sqliteTable("push_settings", {
  ownerUserId: text("owner_user_id").primaryKey(),
  inboundSms: integer("inbound_sms").notNull().default(1),
  unknownSms: integer("unknown_sms").notNull().default(1),
  preview: integer("preview").notNull().default(1),
  quietHours: integer("quiet_hours").notNull().default(0),
  quietStart: text("quiet_start").notNull().default("22:00"),
  quietEnd: text("quiet_end").notNull().default("07:00"),
});
export const pushDeliveries = sqliteTable("push_deliveries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  communicationId: integer("communication_id").notNull().references(() => communications.id),
  endpoint: text("endpoint").notNull(),
  type: text("type").notNull(),
  status: text("status").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, t => [uniqueIndex("idx_push_delivery_once").on(t.communicationId,t.endpoint,t.type)]);

export const campaignTemplates = sqliteTable("campaign_templates", {
  id: integer("id").primaryKey({autoIncrement:true}),
  name: text("name").notNull(), description: text("description"), campaignType: text("campaign_type").notNull(),
  active: integer("active").notNull().default(0), entryCriteria: text("entry_criteria").notNull().default("{}"),
  stopConditions: text("stop_conditions").notNull().default("{}"), completionBehavior: text("completion_behavior").notNull().default("stop"),
  nextCampaignId: integer("next_campaign_id"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const campaignMessages = sqliteTable("campaign_messages", {
  id: integer("id").primaryKey({autoIncrement:true}), name:text("name").notNull(), channel:text("channel").notNull(),
  leadSubtype:text("lead_subtype"), subject:text("subject"), body:text("body").notNull(),
  active:integer("active").notNull().default(1), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const campaignSteps = sqliteTable("campaign_steps", {
  id:integer("id").primaryKey({autoIncrement:true}), campaignId:integer("campaign_id").notNull().references(()=>campaignTemplates.id),
  dayNumber:integer("day_number").notNull(), sequenceOrder:integer("sequence_order").notNull(),
  channel:text("channel").notNull(), relativeDelay:integer("relative_delay").notNull().default(0),
  scheduledTime:text("scheduled_time").notNull().default("10:00"), templateId:integer("template_id").references(()=>campaignMessages.id),
  executionMode:text("execution_mode").notNull(), aiPersonalizationEnabled:integer("ai_personalization_enabled").notNull().default(0),
  skipConditions:text("skip_conditions").notNull().default("{}"), active:integer("active").notNull().default(1),
},t=>[index("idx_campaign_steps_order").on(t.campaignId,t.dayNumber,t.sequenceOrder)]);
export const campaignEnrollments = sqliteTable("campaign_enrollments", {
  id:integer("id").primaryKey({autoIncrement:true}), contactId:integer("contact_id").notNull().references(()=>contacts.id),
  campaignId:integer("campaign_id").notNull().references(()=>campaignTemplates.id), leadSubtype:text("lead_subtype"),
  enrolledAt:text("enrolled_at").notNull(), currentStepId:integer("current_step_id").references(()=>campaignSteps.id),
  nextActionAt:text("next_action_at"), status:text("status").notNull().default("active"), pausedAt:text("paused_at"),
  completedAt:text("completed_at"), stoppedAt:text("stopped_at"), stoppedReason:text("stopped_reason"),
  testMode:integer("test_mode").notNull().default(0), testIntervalMinutes:integer("test_interval_minutes"),
  scheduledTest:integer("scheduled_test").notNull().default(0),scheduleAnchorAt:text("schedule_anchor_at"),
},t=>[index("idx_campaign_due").on(t.status,t.nextActionAt),index("idx_campaign_contact").on(t.contactId)]);
export const campaignExecutions = sqliteTable("campaign_executions", {
  id:integer("id").primaryKey({autoIncrement:true}), enrollmentId:integer("enrollment_id").notNull().references(()=>campaignEnrollments.id),
  stepId:integer("step_id").notNull().references(()=>campaignSteps.id), scheduledAt:text("scheduled_at").notNull(),
  executedAt:text("executed_at"), channel:text("channel").notNull(), templateId:integer("template_id"),
  aiUsed:integer("ai_used").notNull().default(0), aiFailure:text("ai_failure"), finalContent:text("final_content"),
  providerId:text("provider_id"), communicationId:integer("communication_id").references(()=>communications.id),
  taskId:integer("task_id").references(()=>tasks.id), status:text("status").notNull(), skippedReason:text("skipped_reason"),
  error:text("error"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
},t=>[uniqueIndex("idx_campaign_execution_once").on(t.enrollmentId,t.stepId),index("idx_campaign_execution_status").on(t.status)]);
export const campaignSettings = sqliteTable("campaign_settings", {
  id:integer("id").primaryKey(), messageStart:text("message_start").notNull().default("08:00"),
  messageEnd:text("message_end").notNull().default("19:00"), callStart:text("call_start").notNull().default("09:00"),
  callEnd:text("call_end").notNull().default("18:00"), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  schedulerLastRunAt:text("scheduler_last_run_at"),
  automaticSendingEnabled:integer("automatic_sending_enabled").notNull().default(0),
  schedulerLastSuccessAt:text("scheduler_last_success_at"),
  schedulerLastFailureAt:text("scheduler_last_failure_at"),
  schedulerLastFailureReason:text("scheduler_last_failure_reason"),
  schedulerLastProcessed:integer("scheduler_last_processed").notNull().default(0),
});
export const campaignStepTemplates = sqliteTable("campaign_step_templates", {
  stepId:integer("step_id").notNull().references(()=>campaignSteps.id),
  leadSubtype:text("lead_subtype").notNull(),
  templateId:integer("template_id").notNull().references(()=>campaignMessages.id),
},t=>[uniqueIndex("idx_campaign_step_subtype").on(t.stepId,t.leadSubtype)]);

export const transactions = sqliteTable("transactions", {
 id: integer("id").primaryKey({autoIncrement:true}),
 contactId: integer("contact_id").notNull().references(()=>contacts.id),
 propertyId: integer("property_id").references(()=>properties.id),
 legacyOpportunityId: integer("legacy_opportunity_id").unique(),
 side: text("side").notNull(), status: text("status").notNull().default("Preparing"),
 propertyAddress: text("property_address"), leadSource: text("lead_source"), agent: text("agent"),
 sourceSystem: text("source_system"), sourceRecordId: text("source_record_id"), legacyValues: text("legacy_values"),
 closetraqTransactionId: text("closetraq_transaction_id"), closetraqSyncStatus: text("closetraq_sync_status"), closetraqLastSyncedAt: text("closetraq_last_synced_at"), closetraqSyncError: text("closetraq_sync_error"),
 revision: integer("revision").notNull().default(0), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  price_expectation: real("price_expectation"),
  original_list_price: real("original_list_price"),
  current_price: real("current_price"),
  contract_price: real("contract_price"),
  sold_price: real("sold_price"),
  mortgage_balance: real("mortgage_balance"),
  estimated_equity: real("estimated_equity"),
  seller_concessions: real("seller_concessions"),
  buyer_concessions: real("buyer_concessions"),
  estimated_net_proceeds: real("estimated_net_proceeds"),
  final_net_proceeds: real("final_net_proceeds"),
  price_per_square_foot: real("price_per_square_foot"),
  listing_appointment_date: text("listing_appointment_date"),
  listing_agreement_signed_date: text("listing_agreement_signed_date"),
  photos_scheduled_date: text("photos_scheduled_date"),
  photos_completed_date: text("photos_completed_date"),
  repairs_expected_complete_date: text("repairs_expected_complete_date"),
  listing_live_date: text("listing_live_date"),
  original_list_date: text("original_list_date"),
  contract_date: text("contract_date"),
  mutual_acceptance_date: text("mutual_acceptance_date"),
  earnest_money_due: text("earnest_money_due"),
  option_deadline: text("option_deadline"),
  finance_approval_deadline: text("finance_approval_deadline"),
  title_documents_deadline: text("title_documents_deadline"),
  survey_deadline: text("survey_deadline"),
  hoa_documents_deadline: text("hoa_documents_deadline"),
  final_walk_through: text("final_walk_through"),
  close_date: text("close_date"),
  possession_date: text("possession_date"),
  days_on_market: real("days_on_market"),
  number_of_showings: real("number_of_showings"),
  number_of_open_houses: real("number_of_open_houses"),
  number_of_offers: real("number_of_offers"),
  number_of_price_reductions: real("number_of_price_reductions"),
  last_showing_date: text("last_showing_date"),
  showing_feedback: text("showing_feedback"),
  offer_history: text("offer_history"),
  open_house_history: text("open_house_history"),
  listing_activity_notes: text("listing_activity_notes"),
  seller_concerns: text("seller_concerns"),
  motivations: text("motivations"),
  repair_notes: text("repair_notes"),
  negotiation_notes: text("negotiation_notes"),
  transaction_summary: text("transaction_summary"),
  timeline_narrative: text("timeline_narrative"),
  listing_agent: text("listing_agent"),
  other_agent: text("other_agent"),
  buyer_agent: text("buyer_agent"),
  lender: text("lender"),
  title_company: text("title_company"),
  commission: real("commission"),
  agent_split: real("agent_split"),
  team_split: real("team_split"),
  mls_link: text("mls_link"),
  virtual_tour_link: text("virtual_tour_link"),
  photos_link: text("photos_link"),
  other_links: text("other_links"),
},t=>[index("idx_transactions_contact").on(t.contactId),index("idx_transactions_side_status").on(t.side,t.status)]);
export const buyerProfiles = sqliteTable("buyer_profiles", {
 contactId: integer("contact_id").primaryKey().references(()=>contacts.id),
 revision: integer("revision").notNull().default(0), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),legacyValues:text("legacy_values"),
  price_min: real("price_min"),
  price_max: real("price_max"),
  price_ceiling: real("price_ceiling"),
  bedrooms_needed: real("bedrooms_needed"),
  bathrooms_needed: real("bathrooms_needed"),
  minimum_square_footage: real("minimum_square_footage"),
  target_areas_zip_codes: text("target_areas_zip_codes"),
  specific_neighborhoods: text("specific_neighborhoods"),
  specific_schools: text("specific_schools"),
  school_district: text("school_district"),
  maximum_commute_time: real("maximum_commute_time"),
  garage_size_needed: real("garage_size_needed"),
  lot_size_preference: text("lot_size_preference"),
  one_story_preference: integer("one_story_preference"),
  new_construction_preference: integer("new_construction_preference"),
  property_type_preference: text("property_type_preference"),
  must_haves: text("must_haves"),
  nice_to_haves: text("nice_to_haves"),
  deal_breakers: text("deal_breakers"),
  pre_approval_status: text("pre_approval_status"),
  pre_approval_amount: real("pre_approval_amount"),
  lender_contact: text("lender_contact"),
  loan_type: text("loan_type"),
  down_payment: real("down_payment"),
  monthly_payment_target: real("monthly_payment_target"),
  relocating_from: text("relocating_from"),
  lease_end_date: text("lease_end_date"),
  target_move_in_date: text("target_move_in_date"),
  purchase_timeline: text("purchase_timeline"),
  need_to_sell_existing_home_first: integer("need_to_sell_existing_home_first"),
  existing_home_address: text("existing_home_address"),
  household_members: text("household_members"),
  pets: text("pets"),
  household_notes: text("household_notes"),
  first_contact_date: text("first_contact_date"),
  last_showing_date: text("last_showing_date"),
  showings_to_date: real("showings_to_date"),
  offers_written: real("offers_written"),
  offers_accepted: real("offers_accepted"),
  homes_loved_and_lost: text("homes_loved_and_lost"),
  buyer_activity_notes: text("buyer_activity_notes"),
});
export const realEstateHistory = sqliteTable("real_estate_history", {
 id:integer("id").primaryKey({autoIncrement:true}), entityType:text("entity_type").notNull(),entityId:integer("entity_id").notNull(),contactId:integer("contact_id").notNull().references(()=>contacts.id),transactionId:integer("transaction_id").references(()=>transactions.id),
 fieldName:text("field_name").notNull(),oldValue:text("old_value"),newValue:text("new_value"),changedAt:text("changed_at").notNull().default(sql`CURRENT_TIMESTAMP`),changedBy:text("changed_by").notNull(),source:text("source").notNull(),sourceRecordId:text("source_record_id"),sourceDate:text("source_date"),
},t=>[index("idx_re_history_entity").on(t.entityType,t.entityId,t.id)]);
export const transactionContacts = sqliteTable("transaction_contacts",{id:integer("id").primaryKey({autoIncrement:true}),transactionId:integer("transaction_id").notNull().references(()=>transactions.id),contactId:integer("contact_id").notNull().references(()=>contacts.id)},t=>[uniqueIndex("idx_tx_contact_link").on(t.transactionId,t.contactId)]);
export const transactionLinks = sqliteTable("transaction_links",{id:integer("id").primaryKey({autoIncrement:true}),transactionId:integer("transaction_id").notNull().references(()=>transactions.id),kind:text("kind").notNull(),recordId:integer("record_id").notNull()},t=>[uniqueIndex("idx_tx_record_link").on(t.transactionId,t.kind,t.recordId)]);
export const transactionFiles = sqliteTable("transaction_files",{id:integer("id").primaryKey({autoIncrement:true}),transactionId:integer("transaction_id").notNull().references(()=>transactions.id),name:text("name").notNull(),objectKey:text("object_key").notNull(),contentType:text("content_type"),size:integer("size"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
